
<!DOCTYPE html>
<html>
<head>
	<title>Patient</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
 <link rel="stylesheet" type="text/css" href="CSS\DonorPage\Header.css">
 <link rel="stylesheet" type="text/css" href="CSS\DonorPage\Footer.css">	
 <style type="text/css">
 	#dyna{
 		padding: 10px;
 		margin: 20px 0 0 20px;
 		width:400px;
 		height:350px;
 		border:solid 1px green;
 		border-radius: 15px;
 	}
 </style>
</head>
<body>

	<!--HEADER-->

<div class = "Header">
				<ul id = navbar>
					<li class = "normal"><a class="List" href="loggedin.php"><i class="fa fa-home" aria-hidden="true" style = "font-size:30px;"></i> &nbsp;&nbsp;&nbsp;Home</a></li>
					<li class = "normal"><a class="List" href = "#Footer"><i class="fa fa-address-book" aria-hidden="true" style = "font-size:30px;"></i> &nbsp;&nbsp;&nbsp;Contact</a></li>
					<img class ="logo" src="Images/TransparentBackgroundPNG/HeaderLogo.png" height="63px">
					
				</ul>
			</div>
			<br><br>


<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Generate Request
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Requirment</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form id="patient" action="request.php" method="POST">
      <div class="modal-body">
        <div class="form-group row">
              <label for="pname" class="col-sm-2 col-form-label">Patient Name</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" name="pname" id="pname" placeholder="Enter Patient name...">
              </div>
          </div>
          
          <div class="form-group row">
				<label class="col-sm-2 col-form-label"for="bgroup">Blood Group</label>
				<div class="col-sm-10">
					<select name="bgroup" class="form-control" id="bgroup">
						<option disabled selected>Choose Blood Group of the Donor...</option>
						<option value="A+">A RhD positive (A+)</option>
						<option value="A-">A RhD negative (A-)</option>
						<option value="B+">B RhD positive (B+)</option>
						<option value="B-">B RhD negative (B-)</option>
						<option value="O+">O RhD positive (O+)</option>
						<option value="0-">O RhD negative (O-)</option>
						<option value="AB+">AB RhD positive (AB+)</option>
						<option value="AB-">AB RhD negative (AB-)</option>
					</select>
				</div>
		  </div>
      <div class="form-group row">
              <label for="qty" class="col-sm-2 col-form-label">Quantity</label>
              <div class="col-sm-10">
                <input type="number" class="form-control" name="qty" id="qty" placeholder="Enter Quantity...">
              </div>
         
          	
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" name="request" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </div>
</div>
</form>
</div>


<!--REQUETS PENDING-->

 <div id="dyna">
 	<div class="form-group row">
        <label for="preq" class="col-sm-2 col-form-label">Patient Name</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="preq" id="preq" placeholder="">
        </div>
    </div>
	<div class="form-group row">
        <label for="breq" class="col-sm-2 col-form-label">Blood Group</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="breq" id="breq" placeholder="">
        </div>
    </div>
	<div class="form-group row">
        <label for="bqty" class="col-sm-2 col-form-label">Quantity</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="bqty" id="bqty" placeholder="">
        </div>
    </div>
	<div class="form-group row">
        <label for="gen" class="col-sm-2 col-form-label">Generated by</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="gen" id="gen" placeholder="">
        </div>
    </div>
    <button type="submit" name="donate" class="btn btn-primary">Donate</button>
 </div>
</body>
</html>